### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by scontini76** [lkundrak/dev86#15]
It seems to me that the project doesn't have a consistent coding style between modules or even inside the same file. I think that scares a bit new contributors that can't figure out how to handle code changes and editor setting. I suggest to choose a way to write code and apply it to the whole project.

If you give me enough indication on your preferred style I would like to work on make all code conforming to it maybe using some modern tool like clang-format. Then I think that adding or changing code will be easier for everybody.

**Comment by mfld-fr** [comment]
No, thank you, I would like to understand the diff's between the versions :-)

By the way, I suggest you to rather fork from Jody Bruchon's branch, because he is today the most active contributor to DEV86, and we follow him for DEV86 and ELKS.

**Comment by scontini76** [comment]
I see.

**Comment by jbruchon** [comment]
I don't contribute much, I'm more of a maintainer...though I do occasionally add useful things as I find them missing.

**Comment by mfld-fr** [comment]
@jbruchon : yes, but when requesting a pull on yours, it is processed quickly ;-)

**Comment by jbruchon** [comment]
For the record, the coding style issue is caused by the origins of the software: `bcc` and friends are well over 20 years old and were written when K&R C was common. It's been pulled kicking and screaming into the future for Dev86. `bcc` only understands K&R C. `unproto` converts ANSI C declarations to K&R style declarations so `bcc` can compile ANSI C without being internally rewritten for ANSI C. It's likely that an attempt to force cross-project code style consistency will cause a truckload of build problems.

**Comment by mfld-fr** [comment]
Sorry for the mixing of the issues, latest commit actually related to mfld-fr#15, not this one.
